# Generated by Django 3.2.15 on 2022-09-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MYFILEUPLOAD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('file_name', models.CharField(max_length=50)),
                ('file_type', models.FileField(upload_to='documents')),
            ],
        ),
    ]
