# Generated by Django 3.2.15 on 2022-09-19 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MYFILEUPLOAD',
        ),
    ]
