# Generated by Django 3.2.15 on 2022-09-19 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_myfileupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyFileUpload',
        ),
    ]
