# Generated by Django 3.2.15 on 2022-09-19 19:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_myfileupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfileupload',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 19, 19, 26, 45, 621837, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
