# Generated by Django 3.2.15 on 2022-09-19 19:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_alter_myfileupload_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfileupload',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 9, 19, 19, 59, 25, 796166, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
